SRCDIR = ../../main/
SRCS  = $(SRCDIR)/top.sv
SRCS += $(SRCDIR)/prescaler.sv
SRCS += $(SRCDIR)/mother_board.sv
SRCS += $(SRCDIR)/mother_board/cpu.sv
SRCS += $(SRCDIR)/mother_board/rom.sv

include ../../../mk/common-yosys-icestick.mk
